# Generated by Django 5.2.7 on 2025-10-17 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trench', '0006_alter_mfamethod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfamethod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('is_used', models.BooleanField(default=False, verbose_name='is used')),
                ('mfa_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_codes', to='trench.mfamethod', verbose_name='MFA method')),
            ],
            options={
                'verbose_name': 'One-Time Code',
                'verbose_name_plural': 'One-Time Codes',
            },
        ),
    ]
